### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by ygnoh** [ygnoh/chrome-extension-practice#1]
- [x] refresh로 로드될 때도 적용가능 하도록 이벤트 API 찾아보기(`onUpdated` 말고 추가로 뭐 있을듯)
- [x] 버튼 selector 더 상세히 바꾸기 다른 버튼들에 적용 안 되도록
- [x] new Issue / pull request 옆에 + 버튼을 추가해서 template을 고를 수 있도록 해보자
  - pull request merge 옆에 + 버튼과 비슷하게 만들기
- [x] code tab에서 issue 탭으로 이동할 때, 이동하기도 전에 onUpdated 이벤트가 발생하여 아래 에러가 발생
  > Error in event handler for runtime.onMessage: TypeError: Cannot read property 'parentNode' of null
- [x] 드랍다운 마크업 개선
- [ ] issue / pull request를 분리하여 template 제공하기
- [ ] label을 사용자가 입력할 수 있도록 하기
- [ ] repo url에 따라 label 구분지어 입력할 수 있게 하기
- [ ] 버튼 여러개 생성되는 버그 처리
- [ ] 템플릿이 복원되지 않는 현상
  - 템플릿 로드 후 내용 작성하다가 Submit 하지 않는 경우, 다시 이슈를 생성하여도 템플릿이 복원되지 않는다.
  - 깃헙에서 일부러 이렇게 해놓은거 일수도?
- [ ] 템플릿 주입 로직 개선 - [sandbox?!](https://developer.chrome.com/apps/manifest/sandbox)
- [ ] 웹팩 적용? 번들링
